openapi: 3.0.0
info:
  title: Market Bloom API
  version: 1.0.0
servers:
  - url: http://localhost:5000
paths:
  /api/auth/signup:
    post:
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
                - email
                - password
                - userType
              properties:
                name:
                  type: string
                email:
                  type: string
                  format: email
                password:
                  type: string
                userType:
                  type: string
                  enum: [buyer, seller]
      responses:
        '201':
          description: User registered successfully with JWT token
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
        '400':
          description: User already exists
        '500':
          description: Server error

  /api/auth/login:
    post:
      summary: Login user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
      responses:
        '200':
          description: User logged in with JWT token
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
        '400':
          description: Invalid credentials
        '500':
          description: Server error

  /api/shop:
    post:
      summary: Create a new shop (only for sellers)
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - shopName
                - location
                - products
              properties:
                shopName:
                  type: string
                location:
                  type: string
                products:
                  type: array
                  items:
                    type: object
                    required:
                      - name
                      - price
                      - category
                    properties:
                      name:
                        type: string
                      price:
                        type: number
                      category:
                        type: string
      responses:
        '201':
          description: Shop created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  shopId:
                    type: string
                  shopName:
                    type: string
                  location:
                    type: string
                  products:
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                        price:
                          type: number
                        category:
                          type: string
        '401':
          description: Unauthorized (missing or invalid token)
        '500':
          description: Server error

securitySchemes:
  bearerAuth:
    type: http
    scheme: bearer
    bearerFormat: JWT
